Adicionado um novo parceiro
PHPRio/phprio.github.io pull request #50
Opened 2022-06-21 15:57 UTC by cruznicollas

2022-06-21 17:47 UTC, lhsazevedo requested changes
Obrigado! Infelizmente a imagem não está carregando pois a URL utilizada não é um link direto para imagem, e sim para a página do Imgur: https://imgur.com/x6K60W0

Também não sei se é uma boa ideia manter no Imgur, seria mais confiável hospedar no nosso repositório.
Basta salvar o logotipo em `sources/images/locaweb.png` e trocar a URL da configuração para `/images/locaweb.png`.

Aguardo a correção para mesclar!

2022-06-22 16:18 UTC, cruznicollas commented
> Obrigado! Infelizmente a imagem não está carregando pois a URL utilizada não é um link direto para imagem, e sim para a página do Imgur: https://imgur.com/x6K60W0
> 
> Também não sei se é uma boa ideia manter no Imgur, seria mais confiável hospedar no nosso repositório. Basta salvar o logotipo em `sources/images/locaweb.png` e trocar a URL da configuração para `/images/locaweb.png`.
> 
> Aguardo a correção para mesclar!

Refeito!

2022-06-22 17:00 UTC, lhsazevedo requested changes
Quase lá, só faltou remover a pasta `source` do link.
Note que ele deve começar uma barra `/`.

2022-06-22 17:00 UTC, lhsazevedo commented on app/config/sculpin_site.yml
> +    logo: source/images/parceiros/locaweb-removebg-preview.png
```suggestion
    logo: /images/parceiros/locaweb-removebg-preview.png
```

2022-06-22 17:05 UTC, cruznicollas commented
Alterado!

2022-06-22 17:05 UTC, cruznicollas commented on app/config/sculpin_site.yml
> +    logo: source/images/parceiros/locaweb-removebg-preview.png
Alterado!

2022-06-22 17:18 UTC, lhsazevedo approved these changes

2022-06-22 17:19 UTC, merged

2022-06-22 17:22 UTC, lhsazevedo commented
Muito obrigado!